name: Hephaestus
version: 26.1
main: de.erethon.hephaestus.Hephaestus
api-version: '1.21'
bootstrapper: de.erethon.hephaestus.HephaestusBootstrap
dependencies:
  server:
    Hecate:
      load: BEFORE
      required: true
      join-classpath: true
    QuestsXL:
      load: BEFORE
      required: false
      join-classpath: true
    Tyche:
      load: BEFORE
      required: false
      join-classpath: true
